# Generated by Django 5.1.5 on 2025-09-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('gallery', '0006_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.folder'),
        ),
    ]
