# Generated by Django 5.1.5 on 2025-04-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearfolder',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='yearfolder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
