# Generated by Django 5.1.5 on 2025-04-14 10:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_yearfolder_created_at_alter_yearfolder_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearFolder',
            new_name='Folder',
        ),
        migrations.RenameField(
            model_name='uploadimages',
            old_name='year',
            new_name='folder',
        ),
        migrations.AlterField(
            model_name='uploadimages',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
