# Generated by Django 5.1.5 on 2025-06-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_yearfolder_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimages',
            name='title',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
