# Generated by Django 5.1.5 on 2025-06-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_uploadimages_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimages',
            old_name='pic',
            new_name='url',
        ),
    ]
