# Generated by Django 5.1.5 on 2025-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadimages',
            name='uploaded_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadimages',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='uploadimages',
            unique_together={('title', 'folder')},
        ),
    ]
