# Generated by Django 5.1.5 on 2025-09-20 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.ManyToManyField(help_text='Choose which superusers should receive contact form emails.', limit_choices_to={'is_superuser': True}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
