# Generated by Django 5.1.5 on 2025-09-21 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactnotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactnotification",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Choose which superusers should receive contact form emails.",
                limit_choices_to={"is_staff": True},
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
