# Generated by Django 5.1.5 on 2025-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
